;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	easy-kill
	keyboard-escape-quit
	kill-region
	projectile-find-file
	swiper
	))

(setq mc/cmds-to-run-once
      '(
	))
